// packages/react/src/components/Motion.tsx
/**
 * `<Motion>` is a thin declarative wrapper around `play()`. It renders a
 * host element (configurable via `as`) and drives animation via a ref.
 *
 *   <Motion as="div" initial={{ opacity: 0 }} animate={{ opacity: 1 }}
 *           transition={{ duration: 400 }}>
 *     content
 *   </Motion>
 *
 * Variants. `variants` is a named map of `MotionValues`. When `variants`
 * is set, `initial`, `animate`, `exit`, `whileHover`, and `whileTap` may
 * each be either an inline `MotionValues` object, a string key into the
 * variants map, or an array of keys whose values are merged left-to-right
 * (later keys win):
 *
 *   const v = { closed: { x: -100, opacity: 0 }, open: { x: 0, opacity: 1 } }
 *   <Motion variants={v} initial="closed" animate={isOpen ? "open" : "closed"} />
 *
 * Parent-child propagation. A `<Motion>` whose `animate` is a string key
 * propagates that key down to descendant `<Motion>` components that have
 * their own `variants` map but no explicit `animate`. Each descendant
 * resolves the inherited key against its own variants, so a parent flip
 * from "closed" → "open" can drive children with the same vocabulary.
 *
 * whileHover / whileTap. When set, the resolved values from these props
 * temporarily override `animate` while the pointer is over the element
 * (hover) or pressed on it (tap). Tap takes precedence over hover.
 *
 * The resolved `initial` object is applied as inline styles on first
 * render so the element paints at the starting state before any animation
 * frame runs. React state is never updated during playback; all mutation
 * happens on the DOM node via refs.
 */

import type { Controls, EasingFn, NormalizedVelocity, PlayOpts, StrategyTarget } from "@kinem/core"
import { omitUndefined, play, resolveTransition, tween } from "@kinem/core"
import {
  type CSSProperties,
  type ComponentPropsWithoutRef,
  type ElementType,
  type ReactElement,
  type PointerEvent as ReactPointerEvent,
  type Ref,
  createElement,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react"
import {
  MotionAnimateContext,
  type MotionAnimateContextValue,
  type MotionAnimateKey,
} from "./motion-context"
import { PresenceContext } from "./presence"

export type MotionValues = Readonly<Record<string, string | number>>

export type Variants = Readonly<Record<string, MotionValues>>

/**
 * What `initial`, `animate`, `exit`, `whileHover`, and `whileTap` accept:
 * inline values, a single variant key, or a list of keys merged in order
 * (later wins). String / array forms require a `variants` map; otherwise
 * they resolve to `undefined` and the prop is ignored.
 */
export type VariantTarget = MotionValues | string | readonly string[]

export interface MotionTransition {
  /**
   * "tween" (default) plays a fixed-duration easing; "spring" plays a
   * physical spring (stiffness/damping/mass). When omitted, the
   * presence of any spring field implies "spring".
   */
  readonly type?: "tween" | "spring"
  readonly duration?: number
  readonly easing?: EasingFn
  /** Spring: stiffness (default 170). */
  readonly stiffness?: number
  /** Spring: damping (default 26). */
  readonly damping?: number
  /** Spring: mass (default 1). */
  readonly mass?: number
  /**
   * Spring: initial velocity, in normalized [0, 1]/sec units of travel.
   * Mint with `normalizedVelocity()` or `velocityFromSpan()` from
   * `@kinem/core`.
   */
  readonly velocity?: NormalizedVelocity
  readonly backend?: PlayOpts["backend"]
  /**
   * Per-element delay in ms before the tween starts. Composes with any
   * stagger delay inherited from a parent.
   */
  readonly delay?: number
  /**
   * When set on a parent `<Motion>`, descendants that inherit the
   * parent's animate key are staggered by `staggerChildren` ms in
   * mount order: the first child has zero delay, the second
   * `staggerChildren` ms, the third `2 * staggerChildren`, and so on.
   * Applies only to animate-key-driven changes; whileHover and
   * whileTap never stagger.
   */
  readonly staggerChildren?: number
}

type MotionOwnProps<E extends ElementType> = {
  readonly as?: E
  readonly variants?: Variants
  readonly initial?: VariantTarget
  readonly animate?: VariantTarget
  readonly exit?: VariantTarget
  readonly whileHover?: VariantTarget
  readonly whileTap?: VariantTarget
  readonly transition?: MotionTransition
  readonly motionRef?: Ref<Element>
}

export type MotionProps<E extends ElementType = "div"> = MotionOwnProps<E> &
  Omit<ComponentPropsWithoutRef<E>, keyof MotionOwnProps<E>>

function shallowEqualValues(a: MotionValues | undefined, b: MotionValues | undefined): boolean {
  if (a === b) return true
  if (!a || !b) return false
  const aKeys = Object.keys(a)
  const bKeys = Object.keys(b)
  if (aKeys.length !== bKeys.length) return false
  for (const key of aKeys) {
    if (a[key] !== b[key]) return false
  }
  return true
}

function isVariantKey(t: VariantTarget): t is string | readonly string[] {
  return typeof t === "string" || Array.isArray(t)
}

function resolveTarget(
  target: VariantTarget | undefined,
  variants: Variants | undefined,
): MotionValues | undefined {
  if (target === undefined) return undefined
  if (typeof target === "string") {
    return variants?.[target]
  }
  if (Array.isArray(target)) {
    if (!variants) return undefined
    const merged: Record<string, string | number> = {}
    for (const k of target) {
      const v = variants[k]
      if (v) Object.assign(merged, v)
    }
    return merged
  }
  return target as MotionValues
}

function buildTweenProps(
  from: MotionValues,
  to: MotionValues,
): Record<string, readonly [string | number, string | number]> {
  const props: Record<string, readonly [string | number, string | number]> = {}
  for (const key of Object.keys(to)) {
    const fromVal = from[key] ?? to[key]
    const toVal = to[key]
    if (fromVal === undefined || toVal === undefined) continue
    props[key] = [fromVal, toVal]
  }
  return props
}

export function Motion<E extends ElementType = "div">(props: MotionProps<E>): ReactElement {
  const {
    as,
    variants,
    initial,
    animate,
    exit,
    whileHover,
    whileTap,
    transition,
    motionRef,
    style: userStyle,
    children,
    onPointerEnter: userOnPointerEnter,
    onPointerLeave: userOnPointerLeave,
    onPointerDown: userOnPointerDown,
    onPointerUp: userOnPointerUp,
    onPointerCancel: userOnPointerCancel,
    ...rest
  } = props as MotionOwnProps<E> & {
    style?: CSSProperties
    children?: import("react").ReactNode
    onPointerEnter?: (e: ReactPointerEvent<Element>) => void
    onPointerLeave?: (e: ReactPointerEvent<Element>) => void
    onPointerDown?: (e: ReactPointerEvent<Element>) => void
    onPointerUp?: (e: ReactPointerEvent<Element>) => void
    onPointerCancel?: (e: ReactPointerEvent<Element>) => void
  }

  const presence = useContext(PresenceContext)
  const parentCtx = useContext(MotionAnimateContext)
  const parentAnimateKey = parentCtx?.key ?? null

  // A child inherits the parent's animate key only when it has its own
  // variants map and didn't pass an explicit animate of its own. This
  // keeps inheritance opt-in and avoids surprising children that don't
  // share the parent's variant vocabulary.
  const inheritingFromParent = animate === undefined && variants != null && parentAnimateKey != null
  const effectiveAnimate: VariantTarget | undefined =
    animate ?? (inheritingFromParent ? parentAnimateKey : undefined)

  // Claim a stagger index from the parent at first render only when we
  // are actually inheriting the parent's key (otherwise stagger is
  // meaningless). useState's lazy init runs once per logical mount even
  // under StrictMode's double-invoke.
  const [staggerIndex] = useState<number | null>(() =>
    inheritingFromParent && parentCtx?.stagger ? parentCtx.stagger.counter.current++ : null,
  )

  const [hovering, setHovering] = useState(false)
  const [tapping, setTapping] = useState(false)

  // Resolve each target against the variants map. We memo on identity of
  // each input so changing one doesn't churn unrelated work.
  const resolvedInitial = useMemo(() => resolveTarget(initial, variants), [initial, variants])
  const resolvedAnimate = useMemo(
    () => resolveTarget(effectiveAnimate, variants),
    [effectiveAnimate, variants],
  )
  const resolvedExit = useMemo(() => resolveTarget(exit, variants), [exit, variants])
  const resolvedHover = useMemo(() => resolveTarget(whileHover, variants), [whileHover, variants])
  const resolvedTap = useMemo(() => resolveTarget(whileTap, variants), [whileTap, variants])

  // Precedence: tap > hover > animate.
  type TargetSource = "tap" | "hover" | "animate"
  const targetSource: TargetSource =
    tapping && resolvedTap ? "tap" : hovering && resolvedHover ? "hover" : "animate"
  const targetValues: MotionValues | undefined =
    targetSource === "tap"
      ? resolvedTap
      : targetSource === "hover"
        ? resolvedHover
        : resolvedAnimate

  const elRef = useRef<Element | null>(null)
  const controlsRef = useRef<Controls | null>(null)
  const currentValuesRef = useRef<MotionValues | undefined>(resolvedInitial ?? resolvedAnimate)
  const mountedRef = useRef(false)
  // Tracks a setTimeout that defers play() while waiting out a stagger
  // or per-element delay. Cleared on supersede or unmount.
  const startTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const setRef = (el: Element | null): void => {
    elRef.current = el
    if (typeof motionRef === "function") motionRef(el)
    else if (motionRef && "current" in motionRef) {
      ;(motionRef as { current: Element | null }).current = el
    }
  }

  useEffect(() => {
    const el = elRef.current
    if (!el || !targetValues) return
    const from = currentValuesRef.current ?? resolvedInitial ?? targetValues
    const unchanged = mountedRef.current && shallowEqualValues(from, targetValues)
    mountedRef.current = true
    if (unchanged) return

    const existing = controlsRef.current
    if (existing && existing.state !== "cancelled" && existing.state !== "finished") {
      existing.cancel()
    }
    if (startTimerRef.current !== null) {
      clearTimeout(startTimerRef.current)
      startTimerRef.current = null
    }

    const tweenProps = buildTweenProps(from, targetValues)
    if (Object.keys(tweenProps).length === 0) {
      currentValuesRef.current = targetValues
      return
    }

    // Hover/tap never stagger; only animate-key-driven changes do, and
    // only when the parent has set staggerChildren.
    const inheritedStagger =
      targetSource === "animate" &&
      inheritingFromParent &&
      parentCtx?.stagger &&
      staggerIndex != null
        ? staggerIndex * parentCtx.stagger.staggerMs
        : 0
    const totalDelay = inheritedStagger + (transition?.delay ?? 0)

    // Commit the new target eagerly so dependent computations see we're
    // already heading there even while the stagger timer is pending.
    currentValuesRef.current = targetValues
    const start = (): void => {
      const resolved = resolveTransition(transition)
      const def = tween(tweenProps, {
        duration: resolved.duration,
        ...omitUndefined({ easing: resolved.easing }),
      })
      const playOpts: PlayOpts = omitUndefined({ backend: transition?.backend })
      controlsRef.current = play(def, [el as unknown as StrategyTarget], playOpts)
    }
    if (totalDelay > 0) {
      startTimerRef.current = setTimeout(() => {
        startTimerRef.current = null
        start()
      }, totalDelay)
    } else {
      start()
    }
  }, [
    targetValues,
    transition,
    resolvedInitial,
    targetSource,
    inheritingFromParent,
    parentCtx,
    staggerIndex,
  ])

  useEffect(() => {
    if (!presence || presence.isPresent) return
    const el = elRef.current
    if (!el) {
      presence.safeToRemove()
      return
    }
    const existing = controlsRef.current
    if (existing && existing.state !== "cancelled" && existing.state !== "finished") {
      existing.cancel()
    }
    const from = currentValuesRef.current ?? resolvedAnimate ?? resolvedInitial
    if (!resolvedExit || !from) {
      presence.safeToRemove()
      return
    }
    const tweenProps = buildTweenProps(from, resolvedExit)
    if (Object.keys(tweenProps).length === 0) {
      presence.safeToRemove()
      return
    }
    const resolved = resolveTransition(transition)
    const def = tween(tweenProps, {
      duration: resolved.duration,
      ...omitUndefined({ easing: resolved.easing }),
    })
    const playOpts: PlayOpts = omitUndefined({ backend: transition?.backend })
    const controls = play(def, [el as unknown as StrategyTarget], playOpts)
    controlsRef.current = controls
    let removed = false
    const done = (): void => {
      if (removed) return
      removed = true
      presence.safeToRemove()
    }
    controls.finished.then(done, done)
  }, [presence, resolvedExit, resolvedAnimate, resolvedInitial, transition])

  useEffect(() => {
    return () => {
      if (startTimerRef.current !== null) {
        clearTimeout(startTimerRef.current)
        startTimerRef.current = null
      }
      const c = controlsRef.current
      if (c && c.state !== "cancelled" && c.state !== "finished") c.cancel()
      controlsRef.current = null
    }
  }, [])

  // Pointer handlers. We attach our own handler when the corresponding
  // while* prop is set, then call through to any user handler so `onClick`
  // / `onPointerDown` etc. continue to work.
  const onPointerEnter = whileHover
    ? (e: ReactPointerEvent<Element>): void => {
        setHovering(true)
        userOnPointerEnter?.(e)
      }
    : userOnPointerEnter
  const onPointerLeave = whileHover
    ? (e: ReactPointerEvent<Element>): void => {
        setHovering(false)
        // A drag/tap that escapes the element should not stay "tapping"
        // forever; pointerleave clears it too so visual state matches
        // pointer reality even when pointerup never fires.
        setTapping(false)
        userOnPointerLeave?.(e)
      }
    : userOnPointerLeave
  const onPointerDown = whileTap
    ? (e: ReactPointerEvent<Element>): void => {
        setTapping(true)
        userOnPointerDown?.(e)
      }
    : userOnPointerDown
  const onPointerUp = whileTap
    ? (e: ReactPointerEvent<Element>): void => {
        setTapping(false)
        userOnPointerUp?.(e)
      }
    : userOnPointerUp
  const onPointerCancel = whileTap
    ? (e: ReactPointerEvent<Element>): void => {
        setTapping(false)
        userOnPointerCancel?.(e)
      }
    : userOnPointerCancel

  const Tag = (as ?? "div") as ElementType
  const mergedStyle: CSSProperties = {
    ...(resolvedInitial as CSSProperties | undefined),
    ...userStyle,
  }

  // Provide the parent animate key only when our own animate is a key,
  // so descendants can opt into inheritance via their own variants map.
  // The stagger counter is held in a ref so it survives re-renders (so
  // already-mounted children keep their indices when the key flips).
  const staggerCounterRef = useRef<{ current: number }>({ current: 0 })
  const providedKey: MotionAnimateKey =
    effectiveAnimate !== undefined && isVariantKey(effectiveAnimate) ? effectiveAnimate : null
  const provided: MotionAnimateContextValue | null = useMemo(() => {
    if (providedKey === null) return null
    const staggerMs = transition?.staggerChildren
    return {
      key: providedKey,
      stagger:
        staggerMs && staggerMs > 0 ? { staggerMs, counter: staggerCounterRef.current } : null,
    }
  }, [providedKey, transition?.staggerChildren])

  const wrappedChildren =
    provided !== null
      ? createElement(MotionAnimateContext.Provider, { value: provided }, children)
      : children

  return createElement(
    Tag,
    {
      ...(rest as Record<string, unknown>),
      ref: setRef,
      style: mergedStyle,
      onPointerEnter,
      onPointerLeave,
      onPointerDown,
      onPointerUp,
      onPointerCancel,
    },
    wrappedChildren,
  )
}

// packages/solid/src/components/Motion.ts
/**
 * `Motion` is a declarative wrapper around `play()` for Solid. It
 * renders a host element (configurable via the `as` prop) and drives
 * animation via a ref, mirroring the React `<Motion>` and Vue `<Motion>`
 * components.
 *
 *   import { Motion } from "@kinem/solid"
 *
 *   <Motion as="div" initial={{ opacity: 0 }} animate={{ opacity: 1 }}
 *           transition={{ duration: 400 }}>
 *     content
 *   </Motion>
 *
 * Variants. `variants` is a named map of `MotionValues`. When set, the
 * `initial`, `animate`, `exit`, `whileHover`, and `whileTap` props may
 * each be inline values, a single variant key, or an array of keys
 * merged left-to-right (later wins):
 *
 *   const v = { closed: { x: -100, opacity: 0 }, open: { x: 0, opacity: 1 } }
 *   <Motion variants={v} initial="closed" animate={open() ? "open" : "closed"} />
 *
 * Parent-child propagation. A `<Motion>` whose `animate` is a key
 * propagates that key (via context) to descendants that have their own
 * `variants` map but no explicit `animate`. The descendant resolves the
 * inherited key against its own map.
 *
 * whileHover / whileTap. Resolved values from these props temporarily
 * override `animate` while the pointer is over (hover) or pressed
 * (tap). Tap takes precedence over hover.
 *
 * The component is built with Solid's hyperscript (`solid-js/h`) so the
 * Solid package can keep its no-JSX build pipeline.
 *
 * Solid signals are never written during playback; mutation happens
 * directly on the DOM node.
 *
 * Presence integration: when rendered inside a `createPresence`-driven
 * `<Show>` block, set `presence` to the controller. When `presence.isPresent()`
 * flips false, `Motion` plays its `exit` tween (or no-op if absent) and
 * calls `presence.safeToRemove()` once the animation settles.
 */

import type { Controls, EasingFn, NormalizedVelocity, PlayOpts, StrategyTarget } from "@kinem/core"
import { omitUndefined, play, resolveTransition, tween } from "@kinem/core"
import {
  type JSX,
  createEffect,
  createMemo,
  createSignal,
  on,
  onCleanup,
  onMount,
  useContext,
} from "solid-js"
// `solid-js/h` is the hyperscript helper. It returns a Solid JSX node.
// Using it lets this file stay as plain `.ts` so the package's existing
// (no-JSX) build pipeline doesn't need to change.
import h from "solid-js/h"
import type { CreatePresenceResult } from "../primitives/createPresence"
import { MotionAnimateContext, type MotionAnimateContextValue } from "./motion-context"

export type MotionValues = Readonly<Record<string, string | number>>

export type Variants = Readonly<Record<string, MotionValues>>

export type VariantTarget = MotionValues | string | readonly string[]

export interface MotionTransition {
  /**
   * "tween" (default) plays a fixed-duration easing; "spring" plays a
   * physical spring. When omitted, the presence of any spring field
   * implies "spring".
   */
  readonly type?: "tween" | "spring"
  readonly duration?: number
  readonly easing?: EasingFn
  readonly stiffness?: number
  readonly damping?: number
  readonly mass?: number
  /**
   * Spring: initial velocity, in normalized [0, 1]/sec units of travel.
   * Mint with `normalizedVelocity()` or `velocityFromSpan()` from
   * `@kinem/core`.
   */
  readonly velocity?: NormalizedVelocity
  readonly backend?: PlayOpts["backend"]
  /**
   * Per-element delay in ms before the tween starts. Composes with any
   * stagger delay inherited from a parent.
   */
  readonly delay?: number
  /**
   * When set on a parent `<Motion>`, descendants that inherit the
   * parent's animate key are staggered by `staggerChildren` ms in
   * mount order.
   */
  readonly staggerChildren?: number
}

export interface MotionProps {
  readonly as?: string
  readonly variants?: Variants
  readonly initial?: VariantTarget
  readonly animate?: VariantTarget
  readonly exit?: VariantTarget
  readonly whileHover?: VariantTarget
  readonly whileTap?: VariantTarget
  readonly transition?: MotionTransition
  /**
   * Optional presence controller from `createPresence(...)`. When
   * provided and `presence.isPresent()` is false, `Motion` plays the
   * `exit` tween (or skips if `exit` is unset) and calls
   * `presence.safeToRemove()` once the animation settles.
   */
  readonly presence?: CreatePresenceResult
  readonly style?: JSX.CSSProperties
  readonly class?: string
  readonly children?: JSX.Element
  readonly ref?: (el: Element) => void
  readonly [attr: string]: unknown
}

function isVariantKey(t: VariantTarget): t is string | readonly string[] {
  return typeof t === "string" || Array.isArray(t)
}

function resolveTarget(
  target: VariantTarget | undefined,
  variants: Variants | undefined,
): MotionValues | undefined {
  if (target === undefined) return undefined
  if (typeof target === "string") return variants?.[target]
  if (Array.isArray(target)) {
    if (!variants) return undefined
    const merged: Record<string, string | number> = {}
    for (const k of target) {
      const v = variants[k]
      if (v) Object.assign(merged, v)
    }
    return merged
  }
  return target as MotionValues
}

function shallowEqualValues(a: MotionValues | undefined, b: MotionValues | undefined): boolean {
  if (a === b) return true
  if (!a || !b) return false
  const aKeys = Object.keys(a)
  const bKeys = Object.keys(b)
  if (aKeys.length !== bKeys.length) return false
  for (const key of aKeys) {
    if (a[key] !== b[key]) return false
  }
  return true
}

function buildTweenProps(
  from: MotionValues,
  to: MotionValues,
): Record<string, readonly [string | number, string | number]> {
  const props: Record<string, readonly [string | number, string | number]> = {}
  for (const key of Object.keys(to)) {
    const fromVal = from[key] ?? to[key]
    const toVal = to[key]
    if (fromVal === undefined || toVal === undefined) continue
    props[key] = [fromVal, toVal]
  }
  return props
}

export function Motion(props: MotionProps): JSX.Element {
  let el: Element | null = null
  let controls: Controls | null = null
  let mounted = false
  let startTimer: ReturnType<typeof setTimeout> | null = null

  const parentCtx = useContext(MotionAnimateContext)

  const inheritingFromParent = createMemo<boolean>(
    () =>
      props.animate === undefined &&
      props.variants !== undefined &&
      (parentCtx()?.key ?? null) != null,
  )

  // A child inherits the parent's animate key only when it has its own
  // variants map and didn't pass an explicit animate of its own.
  const effectiveAnimate = createMemo<VariantTarget | undefined>(() => {
    if (props.animate !== undefined) return props.animate
    if (inheritingFromParent()) return parentCtx()?.key as VariantTarget
    return undefined
  })

  // Allocate a stagger index lazily on first setup if we are inheriting
  // and the parent has a stagger schedule. The index is captured once.
  const initialCtx = parentCtx()
  const staggerIndex: number | null =
    inheritingFromParent() && initialCtx?.stagger ? initialCtx.stagger.counter.current++ : null

  const [hovering, setHovering] = createSignal(false)
  const [tapping, setTapping] = createSignal(false)

  const resolvedInitial = createMemo(() => resolveTarget(props.initial, props.variants))
  const resolvedAnimate = createMemo(() => resolveTarget(effectiveAnimate(), props.variants))
  const resolvedExit = createMemo(() => resolveTarget(props.exit, props.variants))
  const resolvedHover = createMemo(() => resolveTarget(props.whileHover, props.variants))
  const resolvedTap = createMemo(() => resolveTarget(props.whileTap, props.variants))

  // Tap > hover > animate. Track the source so stagger applies only to
  // animate-key-driven changes.
  type TargetSource = "tap" | "hover" | "animate"
  const targetSource = createMemo<TargetSource>(() => {
    if (tapping() && resolvedTap()) return "tap"
    if (hovering() && resolvedHover()) return "hover"
    return "animate"
  })
  const targetValues = createMemo<MotionValues | undefined>(() => {
    const src = targetSource()
    if (src === "tap") return resolvedTap()
    if (src === "hover") return resolvedHover()
    return resolvedAnimate()
  })

  let currentValues: MotionValues | undefined = resolvedInitial() ?? resolvedAnimate()

  const cancelCurrent = (): void => {
    if (controls && controls.state !== "cancelled" && controls.state !== "finished") {
      controls.cancel()
    }
    controls = null
  }
  const cancelStartTimer = (): void => {
    if (startTimer !== null) {
      clearTimeout(startTimer)
      startTimer = null
    }
  }

  const runTween = (
    from: MotionValues,
    to: MotionValues,
    source: TargetSource,
  ): Controls | null => {
    if (!el) return null
    const tweenProps = buildTweenProps(from, to)
    if (Object.keys(tweenProps).length === 0) return null
    const transition = props.transition
    cancelCurrent()
    cancelStartTimer()

    const ctx = parentCtx()
    const inheritedStagger =
      source === "animate" && inheritingFromParent() && ctx?.stagger && staggerIndex !== null
        ? staggerIndex * ctx.stagger.staggerMs
        : 0
    const totalDelay = inheritedStagger + (transition?.delay ?? 0)

    const start = (): Controls => {
      const resolved = resolveTransition(transition)
      const def = tween(tweenProps, {
        duration: resolved.duration,
        ...omitUndefined({ easing: resolved.easing }),
      })
      const playOpts: PlayOpts = omitUndefined({ backend: transition?.backend })
      controls = play(def, [el as unknown as StrategyTarget], playOpts)
      return controls
    }
    if (totalDelay > 0) {
      startTimer = setTimeout(() => {
        startTimer = null
        start()
      }, totalDelay)
      return null
    }
    return start()
  }

  onMount(() => {
    mounted = true
    const target = targetValues()
    if (!target) return
    const from = currentValues ?? resolvedInitial() ?? target
    runTween(from, target, targetSource())
    currentValues = target
  })

  // Re-tween whenever the resolved target changes after mount.
  createEffect(
    on(
      targetValues,
      (next, prev) => {
        if (!mounted) return
        if (!next) return
        if (shallowEqualValues(next, prev)) return
        const from = currentValues ?? resolvedInitial() ?? next
        if (shallowEqualValues(from, next)) return
        runTween(from, next, targetSource())
        currentValues = next
      },
      { defer: true },
    ),
  )

  // Presence: when isPresent flips false, run the exit tween and notify
  // the controller once it settles.
  if (props.presence) {
    const presence = props.presence
    let exitStarted = false
    createEffect(
      on(
        presence.isPresent,
        (isPresent) => {
          if (isPresent || exitStarted) return
          exitStarted = true
          const from = currentValues ?? resolvedAnimate() ?? resolvedInitial()
          const exitVals = resolvedExit()
          if (!exitVals || !from) {
            presence.safeToRemove()
            return
          }
          const c = runTween(from, exitVals, "animate")
          if (!c) {
            presence.safeToRemove()
            return
          }
          let removed = false
          const done = (): void => {
            if (removed) return
            removed = true
            presence.safeToRemove()
          }
          c.finished.then(done, done)
        },
        { defer: true },
      ),
    )
  }

  onCleanup(() => {
    cancelStartTimer()
    cancelCurrent()
  })

  const setRef = (node: Element): void => {
    el = node
    props.ref?.(node)
  }

  const tag = props.as ?? "div"
  const mergedStyle: JSX.CSSProperties = {
    ...((resolvedInitial() ?? {}) as JSX.CSSProperties),
    ...(props.style ?? {}),
  }

  // Forward unknown props as DOM attributes / event handlers, but strip
  // the motion-specific keys we already consumed and the pointer
  // handlers we wrap below.
  const passThrough: Record<string, unknown> = {}
  let userOnPointerEnter: ((e: PointerEvent) => void) | undefined
  let userOnPointerLeave: ((e: PointerEvent) => void) | undefined
  let userOnPointerDown: ((e: PointerEvent) => void) | undefined
  let userOnPointerUp: ((e: PointerEvent) => void) | undefined
  let userOnPointerCancel: ((e: PointerEvent) => void) | undefined

  for (const key of Object.keys(props)) {
    if (
      key === "as" ||
      key === "variants" ||
      key === "initial" ||
      key === "animate" ||
      key === "exit" ||
      key === "whileHover" ||
      key === "whileTap" ||
      key === "transition" ||
      key === "presence" ||
      key === "style" ||
      key === "ref" ||
      key === "children"
    ) {
      continue
    }
    if (key === "onPointerEnter" || key === "onpointerenter") {
      userOnPointerEnter = props[key] as (e: PointerEvent) => void
      continue
    }
    if (key === "onPointerLeave" || key === "onpointerleave") {
      userOnPointerLeave = props[key] as (e: PointerEvent) => void
      continue
    }
    if (key === "onPointerDown" || key === "onpointerdown") {
      userOnPointerDown = props[key] as (e: PointerEvent) => void
      continue
    }
    if (key === "onPointerUp" || key === "onpointerup") {
      userOnPointerUp = props[key] as (e: PointerEvent) => void
      continue
    }
    if (key === "onPointerCancel" || key === "onpointercancel") {
      userOnPointerCancel = props[key] as (e: PointerEvent) => void
      continue
    }
    passThrough[key] = props[key]
  }

  if (props.whileHover !== undefined) {
    passThrough["onPointerEnter"] = (e: PointerEvent): void => {
      setHovering(true)
      userOnPointerEnter?.(e)
    }
    passThrough["onPointerLeave"] = (e: PointerEvent): void => {
      setHovering(false)
      setTapping(false)
      userOnPointerLeave?.(e)
    }
  } else {
    if (userOnPointerEnter) passThrough["onPointerEnter"] = userOnPointerEnter
    if (userOnPointerLeave) passThrough["onPointerLeave"] = userOnPointerLeave
  }
  if (props.whileTap !== undefined) {
    passThrough["onPointerDown"] = (e: PointerEvent): void => {
      setTapping(true)
      userOnPointerDown?.(e)
    }
    passThrough["onPointerUp"] = (e: PointerEvent): void => {
      setTapping(false)
      userOnPointerUp?.(e)
    }
    passThrough["onPointerCancel"] = (e: PointerEvent): void => {
      setTapping(false)
      userOnPointerCancel?.(e)
    }
  } else {
    if (userOnPointerDown) passThrough["onPointerDown"] = userOnPointerDown
    if (userOnPointerUp) passThrough["onPointerUp"] = userOnPointerUp
    if (userOnPointerCancel) passThrough["onPointerCancel"] = userOnPointerCancel
  }

  // Provide the parent animate key only when our own animate is a key,
  // so descendants can opt into inheritance via their own variants map.
  // The stagger counter is held outside the memo so it survives re-runs
  // when only effectiveAnimate changes.
  const staggerCounter = { current: 0 }
  const provideValue = createMemo<MotionAnimateContextValue | null>(() => {
    const a = effectiveAnimate()
    const key = a !== undefined && isVariantKey(a) ? a : null
    if (key === null) return null
    const staggerMs = props.transition?.staggerChildren
    return {
      key,
      stagger: staggerMs && staggerMs > 0 ? { staggerMs, counter: staggerCounter } : null,
    }
  })

  const node = h(
    tag,
    { ...passThrough, ref: setRef, style: mergedStyle },
    props.children,
  ) as unknown as JSX.Element

  return h(MotionAnimateContext.Provider, { value: provideValue }, node) as unknown as JSX.Element
}
